name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      PROPEL_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      PROPEL_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      

    - name: Build
      run: go build -v ./...

    - name: Test
      run: TF_ACC=1 go test -v ./...